# env: the system of your PC (e.g. windows, macOS, Linux)
env: windows

# system: the target harmonyOS
system: harmonyOS

# device: <device serial>
# output_dir: <output path>
# app_path: target .hap file
# count: <number of events to input>

device: 127.0.0.1:5555
output_dir: output
app_path: D:\Users\John\PycharmProjects\HMDroidbot\orangeMall.hap
#count: 100
#task: "随便点击一件商品进入详情页，然后点击立即购买，提交订单,并成功支付，都完成后停止app即可"
#task: "点击购物车，选择购物车的所有商品，进行结算，提交订单,并成功支付，都完成后停止app即可"
task: "选择最下面的商品，进入详情页，然后点击立即购买，提交订单,并成功支付，都完成后停止app即可"